export const GET_SCHOOL = 'GET_SCHOOL';
export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',
};

export const dataConstants = {
   FETCH_PENDING: 'DATA_FETCH_PENDING',
   FETCH_SUCCESS: 'DATA_FETCH_SUCCESS',
   FETCH_FAILURE: 'DATA_FETCH_FAILURE',

};
